# Generated by Django 2.0.5 on 2018-06-08 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_recreate_eventrun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(
                choices=[
                    ('FN', 'fun'), 
                    ('RX', 'relax'), 
                    ('EX', 'experience'), 
                    ('SI', 'sights')], 
                default='FN', max_length=20),
        ),
    ]
